[theme]
primaryColor = "#373d37ff"          # Button/slider/highlight color
backgroundColor = "#FFFFFF"       # App background
secondaryBackgroundColor = "#F0F2F6"  # Sidebar background
textColor = "#000000"             # Main text color
font = "sans serif"               # Options: "sans serif", "serif", "monospace"
